### ISSUE TITLE
`npm install artoo-js`?

### ISSUE THREAD

**Issue by christiangenco** [a7medkamel/taskmill-onebox#5]
I'm not sure of the process for requesting a new npm package to the [list of npm packages already installed](https://taskmill.io/help/package), but could I get [artoo-js](https://github.com/medialab/artoo)?

**Comment by a7medkamel** [comment]
done / let me know if you need help with your script or need any other packages

**Comment by christiangenco** [comment]
Awesome - thank you! :smile:
